package org.terasoluna.batch.job02;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.springframework.format.annotation.DateTimeFormat;
import org.terasoluna.batch.common.model.AbstractModel;
import org.terasoluna.batch.common.validation.IsDate;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table VARIABLE
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class Variable extends AbstractModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.CODE
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.DATE1
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy/MM/dd")
    private LocalDate date1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.DATE2
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy/MM/dd")
    private LocalDate date2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.DATE3
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy/MM/dd")
    private LocalDate date3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.DATE4
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy/MM/dd")
    private LocalDate date4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.DATE5
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy/MM/dd")
    private LocalDate date5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.FILE1UUID
     *
     * @mbg.generated
     */
    private String file1uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALINT1
     *
     * @mbg.generated
     */
    private Integer valint1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALINT2
     *
     * @mbg.generated
     */
    private Integer valint2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALINT3
     *
     * @mbg.generated
     */
    private Integer valint3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALINT4
     *
     * @mbg.generated
     */
    private Integer valint4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALINT5
     *
     * @mbg.generated
     */
    private Integer valint5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE1
     *
     * @mbg.generated
     */
    private String value1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE10
     *
     * @mbg.generated
     */
    private String value10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE2
     *
     * @mbg.generated
     */
    private String value2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE3
     *
     * @mbg.generated
     */
    private String value3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE4
     *
     * @mbg.generated
     */
    private String value4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE5
     *
     * @mbg.generated
     */
    private String value5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE6
     *
     * @mbg.generated
     */
    private String value6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE7
     *
     * @mbg.generated
     */
    private String value7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE8
     *
     * @mbg.generated
     */
    private String value8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.VALUE9
     *
     * @mbg.generated
     */
    private String value9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VARIABLE.TEXTAREA
     *
     * @mbg.generated
     */
    private String textarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}