package org.terasoluna.batch.job02;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.terasoluna.batch.job02.Variable;
import org.terasoluna.batch.job02.VariableExample;

public interface VariableRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    long countByExample(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int deleteByExample(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int insert(Variable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int insertSelective(Variable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    List<Variable> selectByExampleWithBLOBsWithRowbounds(VariableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    List<Variable> selectByExampleWithBLOBs(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    List<Variable> selectByExampleWithRowbounds(VariableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    List<Variable> selectByExample(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    Variable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Variable record, @Param("example") VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Variable record, @Param("example") VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Variable record, @Param("example") VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Variable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Variable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Variable record);
}