package org.terasoluna.batch.job02;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class VariableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public VariableExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("CREATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("CREATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(LocalDateTime value) {
            addCriterion("CREATED_DATE =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(LocalDateTime value) {
            addCriterion("CREATED_DATE <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(LocalDateTime value) {
            addCriterion("CREATED_DATE >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATED_DATE >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(LocalDateTime value) {
            addCriterion("CREATED_DATE <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATED_DATE <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<LocalDateTime> values) {
            addCriterion("CREATED_DATE in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<LocalDateTime> values) {
            addCriterion("CREATED_DATE not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATED_DATE between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATED_DATE not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNull() {
            addCriterion("LAST_MODIFIED_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNotNull() {
            addCriterion("LAST_MODIFIED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByEqualTo(String value) {
            addCriterion("LAST_MODIFIED_BY =", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotEqualTo(String value) {
            addCriterion("LAST_MODIFIED_BY <>", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThan(String value) {
            addCriterion("LAST_MODIFIED_BY >", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_MODIFIED_BY >=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThan(String value) {
            addCriterion("LAST_MODIFIED_BY <", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThanOrEqualTo(String value) {
            addCriterion("LAST_MODIFIED_BY <=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLike(String value) {
            addCriterion("LAST_MODIFIED_BY like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotLike(String value) {
            addCriterion("LAST_MODIFIED_BY not like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIn(List<String> values) {
            addCriterion("LAST_MODIFIED_BY in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotIn(List<String> values) {
            addCriterion("LAST_MODIFIED_BY not in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByBetween(String value1, String value2) {
            addCriterion("LAST_MODIFIED_BY between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotBetween(String value1, String value2) {
            addCriterion("LAST_MODIFIED_BY not between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("LAST_MODIFIED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("LAST_MODIFIED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(LocalDateTime value) {
            addCriterion("LAST_MODIFIED_DATE =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(LocalDateTime value) {
            addCriterion("LAST_MODIFIED_DATE <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(LocalDateTime value) {
            addCriterion("LAST_MODIFIED_DATE >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("LAST_MODIFIED_DATE >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(LocalDateTime value) {
            addCriterion("LAST_MODIFIED_DATE <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("LAST_MODIFIED_DATE <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<LocalDateTime> values) {
            addCriterion("LAST_MODIFIED_DATE in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<LocalDateTime> values) {
            addCriterion("LAST_MODIFIED_DATE not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("LAST_MODIFIED_DATE between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("LAST_MODIFIED_DATE not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andDate1IsNull() {
            addCriterion("DATE1 is null");
            return (Criteria) this;
        }

        public Criteria andDate1IsNotNull() {
            addCriterion("DATE1 is not null");
            return (Criteria) this;
        }

        public Criteria andDate1EqualTo(LocalDate value) {
            addCriterion("DATE1 =", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1NotEqualTo(LocalDate value) {
            addCriterion("DATE1 <>", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1GreaterThan(LocalDate value) {
            addCriterion("DATE1 >", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("DATE1 >=", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1LessThan(LocalDate value) {
            addCriterion("DATE1 <", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1LessThanOrEqualTo(LocalDate value) {
            addCriterion("DATE1 <=", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1In(List<LocalDate> values) {
            addCriterion("DATE1 in", values, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1NotIn(List<LocalDate> values) {
            addCriterion("DATE1 not in", values, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1Between(LocalDate value1, LocalDate value2) {
            addCriterion("DATE1 between", value1, value2, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("DATE1 not between", value1, value2, "date1");
            return (Criteria) this;
        }

        public Criteria andDate2IsNull() {
            addCriterion("DATE2 is null");
            return (Criteria) this;
        }

        public Criteria andDate2IsNotNull() {
            addCriterion("DATE2 is not null");
            return (Criteria) this;
        }

        public Criteria andDate2EqualTo(LocalDate value) {
            addCriterion("DATE2 =", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2NotEqualTo(LocalDate value) {
            addCriterion("DATE2 <>", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2GreaterThan(LocalDate value) {
            addCriterion("DATE2 >", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("DATE2 >=", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2LessThan(LocalDate value) {
            addCriterion("DATE2 <", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2LessThanOrEqualTo(LocalDate value) {
            addCriterion("DATE2 <=", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2In(List<LocalDate> values) {
            addCriterion("DATE2 in", values, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2NotIn(List<LocalDate> values) {
            addCriterion("DATE2 not in", values, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2Between(LocalDate value1, LocalDate value2) {
            addCriterion("DATE2 between", value1, value2, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("DATE2 not between", value1, value2, "date2");
            return (Criteria) this;
        }

        public Criteria andDate3IsNull() {
            addCriterion("DATE3 is null");
            return (Criteria) this;
        }

        public Criteria andDate3IsNotNull() {
            addCriterion("DATE3 is not null");
            return (Criteria) this;
        }

        public Criteria andDate3EqualTo(LocalDate value) {
            addCriterion("DATE3 =", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3NotEqualTo(LocalDate value) {
            addCriterion("DATE3 <>", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3GreaterThan(LocalDate value) {
            addCriterion("DATE3 >", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("DATE3 >=", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3LessThan(LocalDate value) {
            addCriterion("DATE3 <", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3LessThanOrEqualTo(LocalDate value) {
            addCriterion("DATE3 <=", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3In(List<LocalDate> values) {
            addCriterion("DATE3 in", values, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3NotIn(List<LocalDate> values) {
            addCriterion("DATE3 not in", values, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3Between(LocalDate value1, LocalDate value2) {
            addCriterion("DATE3 between", value1, value2, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("DATE3 not between", value1, value2, "date3");
            return (Criteria) this;
        }

        public Criteria andDate4IsNull() {
            addCriterion("DATE4 is null");
            return (Criteria) this;
        }

        public Criteria andDate4IsNotNull() {
            addCriterion("DATE4 is not null");
            return (Criteria) this;
        }

        public Criteria andDate4EqualTo(LocalDate value) {
            addCriterion("DATE4 =", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4NotEqualTo(LocalDate value) {
            addCriterion("DATE4 <>", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4GreaterThan(LocalDate value) {
            addCriterion("DATE4 >", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("DATE4 >=", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4LessThan(LocalDate value) {
            addCriterion("DATE4 <", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4LessThanOrEqualTo(LocalDate value) {
            addCriterion("DATE4 <=", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4In(List<LocalDate> values) {
            addCriterion("DATE4 in", values, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4NotIn(List<LocalDate> values) {
            addCriterion("DATE4 not in", values, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4Between(LocalDate value1, LocalDate value2) {
            addCriterion("DATE4 between", value1, value2, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("DATE4 not between", value1, value2, "date4");
            return (Criteria) this;
        }

        public Criteria andDate5IsNull() {
            addCriterion("DATE5 is null");
            return (Criteria) this;
        }

        public Criteria andDate5IsNotNull() {
            addCriterion("DATE5 is not null");
            return (Criteria) this;
        }

        public Criteria andDate5EqualTo(LocalDate value) {
            addCriterion("DATE5 =", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5NotEqualTo(LocalDate value) {
            addCriterion("DATE5 <>", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5GreaterThan(LocalDate value) {
            addCriterion("DATE5 >", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("DATE5 >=", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5LessThan(LocalDate value) {
            addCriterion("DATE5 <", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5LessThanOrEqualTo(LocalDate value) {
            addCriterion("DATE5 <=", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5In(List<LocalDate> values) {
            addCriterion("DATE5 in", values, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5NotIn(List<LocalDate> values) {
            addCriterion("DATE5 not in", values, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5Between(LocalDate value1, LocalDate value2) {
            addCriterion("DATE5 between", value1, value2, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("DATE5 not between", value1, value2, "date5");
            return (Criteria) this;
        }

        public Criteria andFile1uuidIsNull() {
            addCriterion("FILE1UUID is null");
            return (Criteria) this;
        }

        public Criteria andFile1uuidIsNotNull() {
            addCriterion("FILE1UUID is not null");
            return (Criteria) this;
        }

        public Criteria andFile1uuidEqualTo(String value) {
            addCriterion("FILE1UUID =", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidNotEqualTo(String value) {
            addCriterion("FILE1UUID <>", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidGreaterThan(String value) {
            addCriterion("FILE1UUID >", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidGreaterThanOrEqualTo(String value) {
            addCriterion("FILE1UUID >=", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidLessThan(String value) {
            addCriterion("FILE1UUID <", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidLessThanOrEqualTo(String value) {
            addCriterion("FILE1UUID <=", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidLike(String value) {
            addCriterion("FILE1UUID like", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidNotLike(String value) {
            addCriterion("FILE1UUID not like", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidIn(List<String> values) {
            addCriterion("FILE1UUID in", values, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidNotIn(List<String> values) {
            addCriterion("FILE1UUID not in", values, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidBetween(String value1, String value2) {
            addCriterion("FILE1UUID between", value1, value2, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidNotBetween(String value1, String value2) {
            addCriterion("FILE1UUID not between", value1, value2, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andValint1IsNull() {
            addCriterion("VALINT1 is null");
            return (Criteria) this;
        }

        public Criteria andValint1IsNotNull() {
            addCriterion("VALINT1 is not null");
            return (Criteria) this;
        }

        public Criteria andValint1EqualTo(Integer value) {
            addCriterion("VALINT1 =", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1NotEqualTo(Integer value) {
            addCriterion("VALINT1 <>", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1GreaterThan(Integer value) {
            addCriterion("VALINT1 >", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1GreaterThanOrEqualTo(Integer value) {
            addCriterion("VALINT1 >=", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1LessThan(Integer value) {
            addCriterion("VALINT1 <", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1LessThanOrEqualTo(Integer value) {
            addCriterion("VALINT1 <=", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1In(List<Integer> values) {
            addCriterion("VALINT1 in", values, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1NotIn(List<Integer> values) {
            addCriterion("VALINT1 not in", values, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1Between(Integer value1, Integer value2) {
            addCriterion("VALINT1 between", value1, value2, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1NotBetween(Integer value1, Integer value2) {
            addCriterion("VALINT1 not between", value1, value2, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint2IsNull() {
            addCriterion("VALINT2 is null");
            return (Criteria) this;
        }

        public Criteria andValint2IsNotNull() {
            addCriterion("VALINT2 is not null");
            return (Criteria) this;
        }

        public Criteria andValint2EqualTo(Integer value) {
            addCriterion("VALINT2 =", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2NotEqualTo(Integer value) {
            addCriterion("VALINT2 <>", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2GreaterThan(Integer value) {
            addCriterion("VALINT2 >", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2GreaterThanOrEqualTo(Integer value) {
            addCriterion("VALINT2 >=", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2LessThan(Integer value) {
            addCriterion("VALINT2 <", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2LessThanOrEqualTo(Integer value) {
            addCriterion("VALINT2 <=", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2In(List<Integer> values) {
            addCriterion("VALINT2 in", values, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2NotIn(List<Integer> values) {
            addCriterion("VALINT2 not in", values, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2Between(Integer value1, Integer value2) {
            addCriterion("VALINT2 between", value1, value2, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2NotBetween(Integer value1, Integer value2) {
            addCriterion("VALINT2 not between", value1, value2, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint3IsNull() {
            addCriterion("VALINT3 is null");
            return (Criteria) this;
        }

        public Criteria andValint3IsNotNull() {
            addCriterion("VALINT3 is not null");
            return (Criteria) this;
        }

        public Criteria andValint3EqualTo(Integer value) {
            addCriterion("VALINT3 =", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3NotEqualTo(Integer value) {
            addCriterion("VALINT3 <>", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3GreaterThan(Integer value) {
            addCriterion("VALINT3 >", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3GreaterThanOrEqualTo(Integer value) {
            addCriterion("VALINT3 >=", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3LessThan(Integer value) {
            addCriterion("VALINT3 <", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3LessThanOrEqualTo(Integer value) {
            addCriterion("VALINT3 <=", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3In(List<Integer> values) {
            addCriterion("VALINT3 in", values, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3NotIn(List<Integer> values) {
            addCriterion("VALINT3 not in", values, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3Between(Integer value1, Integer value2) {
            addCriterion("VALINT3 between", value1, value2, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3NotBetween(Integer value1, Integer value2) {
            addCriterion("VALINT3 not between", value1, value2, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint4IsNull() {
            addCriterion("VALINT4 is null");
            return (Criteria) this;
        }

        public Criteria andValint4IsNotNull() {
            addCriterion("VALINT4 is not null");
            return (Criteria) this;
        }

        public Criteria andValint4EqualTo(Integer value) {
            addCriterion("VALINT4 =", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4NotEqualTo(Integer value) {
            addCriterion("VALINT4 <>", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4GreaterThan(Integer value) {
            addCriterion("VALINT4 >", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4GreaterThanOrEqualTo(Integer value) {
            addCriterion("VALINT4 >=", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4LessThan(Integer value) {
            addCriterion("VALINT4 <", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4LessThanOrEqualTo(Integer value) {
            addCriterion("VALINT4 <=", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4In(List<Integer> values) {
            addCriterion("VALINT4 in", values, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4NotIn(List<Integer> values) {
            addCriterion("VALINT4 not in", values, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4Between(Integer value1, Integer value2) {
            addCriterion("VALINT4 between", value1, value2, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4NotBetween(Integer value1, Integer value2) {
            addCriterion("VALINT4 not between", value1, value2, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint5IsNull() {
            addCriterion("VALINT5 is null");
            return (Criteria) this;
        }

        public Criteria andValint5IsNotNull() {
            addCriterion("VALINT5 is not null");
            return (Criteria) this;
        }

        public Criteria andValint5EqualTo(Integer value) {
            addCriterion("VALINT5 =", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5NotEqualTo(Integer value) {
            addCriterion("VALINT5 <>", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5GreaterThan(Integer value) {
            addCriterion("VALINT5 >", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5GreaterThanOrEqualTo(Integer value) {
            addCriterion("VALINT5 >=", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5LessThan(Integer value) {
            addCriterion("VALINT5 <", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5LessThanOrEqualTo(Integer value) {
            addCriterion("VALINT5 <=", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5In(List<Integer> values) {
            addCriterion("VALINT5 in", values, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5NotIn(List<Integer> values) {
            addCriterion("VALINT5 not in", values, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5Between(Integer value1, Integer value2) {
            addCriterion("VALINT5 between", value1, value2, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5NotBetween(Integer value1, Integer value2) {
            addCriterion("VALINT5 not between", value1, value2, "valint5");
            return (Criteria) this;
        }

        public Criteria andValue1IsNull() {
            addCriterion("VALUE1 is null");
            return (Criteria) this;
        }

        public Criteria andValue1IsNotNull() {
            addCriterion("VALUE1 is not null");
            return (Criteria) this;
        }

        public Criteria andValue1EqualTo(String value) {
            addCriterion("VALUE1 =", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1NotEqualTo(String value) {
            addCriterion("VALUE1 <>", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1GreaterThan(String value) {
            addCriterion("VALUE1 >", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE1 >=", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1LessThan(String value) {
            addCriterion("VALUE1 <", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1LessThanOrEqualTo(String value) {
            addCriterion("VALUE1 <=", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1Like(String value) {
            addCriterion("VALUE1 like", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1NotLike(String value) {
            addCriterion("VALUE1 not like", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1In(List<String> values) {
            addCriterion("VALUE1 in", values, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1NotIn(List<String> values) {
            addCriterion("VALUE1 not in", values, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1Between(String value1, String value2) {
            addCriterion("VALUE1 between", value1, value2, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1NotBetween(String value1, String value2) {
            addCriterion("VALUE1 not between", value1, value2, "value1");
            return (Criteria) this;
        }

        public Criteria andValue10IsNull() {
            addCriterion("VALUE10 is null");
            return (Criteria) this;
        }

        public Criteria andValue10IsNotNull() {
            addCriterion("VALUE10 is not null");
            return (Criteria) this;
        }

        public Criteria andValue10EqualTo(String value) {
            addCriterion("VALUE10 =", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10NotEqualTo(String value) {
            addCriterion("VALUE10 <>", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10GreaterThan(String value) {
            addCriterion("VALUE10 >", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE10 >=", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10LessThan(String value) {
            addCriterion("VALUE10 <", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10LessThanOrEqualTo(String value) {
            addCriterion("VALUE10 <=", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10Like(String value) {
            addCriterion("VALUE10 like", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10NotLike(String value) {
            addCriterion("VALUE10 not like", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10In(List<String> values) {
            addCriterion("VALUE10 in", values, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10NotIn(List<String> values) {
            addCriterion("VALUE10 not in", values, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10Between(String value1, String value2) {
            addCriterion("VALUE10 between", value1, value2, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10NotBetween(String value1, String value2) {
            addCriterion("VALUE10 not between", value1, value2, "value10");
            return (Criteria) this;
        }

        public Criteria andValue2IsNull() {
            addCriterion("VALUE2 is null");
            return (Criteria) this;
        }

        public Criteria andValue2IsNotNull() {
            addCriterion("VALUE2 is not null");
            return (Criteria) this;
        }

        public Criteria andValue2EqualTo(String value) {
            addCriterion("VALUE2 =", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2NotEqualTo(String value) {
            addCriterion("VALUE2 <>", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2GreaterThan(String value) {
            addCriterion("VALUE2 >", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE2 >=", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2LessThan(String value) {
            addCriterion("VALUE2 <", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2LessThanOrEqualTo(String value) {
            addCriterion("VALUE2 <=", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2Like(String value) {
            addCriterion("VALUE2 like", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2NotLike(String value) {
            addCriterion("VALUE2 not like", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2In(List<String> values) {
            addCriterion("VALUE2 in", values, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2NotIn(List<String> values) {
            addCriterion("VALUE2 not in", values, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2Between(String value1, String value2) {
            addCriterion("VALUE2 between", value1, value2, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2NotBetween(String value1, String value2) {
            addCriterion("VALUE2 not between", value1, value2, "value2");
            return (Criteria) this;
        }

        public Criteria andValue3IsNull() {
            addCriterion("VALUE3 is null");
            return (Criteria) this;
        }

        public Criteria andValue3IsNotNull() {
            addCriterion("VALUE3 is not null");
            return (Criteria) this;
        }

        public Criteria andValue3EqualTo(String value) {
            addCriterion("VALUE3 =", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3NotEqualTo(String value) {
            addCriterion("VALUE3 <>", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3GreaterThan(String value) {
            addCriterion("VALUE3 >", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE3 >=", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3LessThan(String value) {
            addCriterion("VALUE3 <", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3LessThanOrEqualTo(String value) {
            addCriterion("VALUE3 <=", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3Like(String value) {
            addCriterion("VALUE3 like", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3NotLike(String value) {
            addCriterion("VALUE3 not like", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3In(List<String> values) {
            addCriterion("VALUE3 in", values, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3NotIn(List<String> values) {
            addCriterion("VALUE3 not in", values, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3Between(String value1, String value2) {
            addCriterion("VALUE3 between", value1, value2, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3NotBetween(String value1, String value2) {
            addCriterion("VALUE3 not between", value1, value2, "value3");
            return (Criteria) this;
        }

        public Criteria andValue4IsNull() {
            addCriterion("VALUE4 is null");
            return (Criteria) this;
        }

        public Criteria andValue4IsNotNull() {
            addCriterion("VALUE4 is not null");
            return (Criteria) this;
        }

        public Criteria andValue4EqualTo(String value) {
            addCriterion("VALUE4 =", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4NotEqualTo(String value) {
            addCriterion("VALUE4 <>", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4GreaterThan(String value) {
            addCriterion("VALUE4 >", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE4 >=", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4LessThan(String value) {
            addCriterion("VALUE4 <", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4LessThanOrEqualTo(String value) {
            addCriterion("VALUE4 <=", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4Like(String value) {
            addCriterion("VALUE4 like", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4NotLike(String value) {
            addCriterion("VALUE4 not like", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4In(List<String> values) {
            addCriterion("VALUE4 in", values, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4NotIn(List<String> values) {
            addCriterion("VALUE4 not in", values, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4Between(String value1, String value2) {
            addCriterion("VALUE4 between", value1, value2, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4NotBetween(String value1, String value2) {
            addCriterion("VALUE4 not between", value1, value2, "value4");
            return (Criteria) this;
        }

        public Criteria andValue5IsNull() {
            addCriterion("VALUE5 is null");
            return (Criteria) this;
        }

        public Criteria andValue5IsNotNull() {
            addCriterion("VALUE5 is not null");
            return (Criteria) this;
        }

        public Criteria andValue5EqualTo(String value) {
            addCriterion("VALUE5 =", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5NotEqualTo(String value) {
            addCriterion("VALUE5 <>", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5GreaterThan(String value) {
            addCriterion("VALUE5 >", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE5 >=", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5LessThan(String value) {
            addCriterion("VALUE5 <", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5LessThanOrEqualTo(String value) {
            addCriterion("VALUE5 <=", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5Like(String value) {
            addCriterion("VALUE5 like", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5NotLike(String value) {
            addCriterion("VALUE5 not like", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5In(List<String> values) {
            addCriterion("VALUE5 in", values, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5NotIn(List<String> values) {
            addCriterion("VALUE5 not in", values, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5Between(String value1, String value2) {
            addCriterion("VALUE5 between", value1, value2, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5NotBetween(String value1, String value2) {
            addCriterion("VALUE5 not between", value1, value2, "value5");
            return (Criteria) this;
        }

        public Criteria andValue6IsNull() {
            addCriterion("VALUE6 is null");
            return (Criteria) this;
        }

        public Criteria andValue6IsNotNull() {
            addCriterion("VALUE6 is not null");
            return (Criteria) this;
        }

        public Criteria andValue6EqualTo(String value) {
            addCriterion("VALUE6 =", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6NotEqualTo(String value) {
            addCriterion("VALUE6 <>", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6GreaterThan(String value) {
            addCriterion("VALUE6 >", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE6 >=", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6LessThan(String value) {
            addCriterion("VALUE6 <", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6LessThanOrEqualTo(String value) {
            addCriterion("VALUE6 <=", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6Like(String value) {
            addCriterion("VALUE6 like", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6NotLike(String value) {
            addCriterion("VALUE6 not like", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6In(List<String> values) {
            addCriterion("VALUE6 in", values, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6NotIn(List<String> values) {
            addCriterion("VALUE6 not in", values, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6Between(String value1, String value2) {
            addCriterion("VALUE6 between", value1, value2, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6NotBetween(String value1, String value2) {
            addCriterion("VALUE6 not between", value1, value2, "value6");
            return (Criteria) this;
        }

        public Criteria andValue7IsNull() {
            addCriterion("VALUE7 is null");
            return (Criteria) this;
        }

        public Criteria andValue7IsNotNull() {
            addCriterion("VALUE7 is not null");
            return (Criteria) this;
        }

        public Criteria andValue7EqualTo(String value) {
            addCriterion("VALUE7 =", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7NotEqualTo(String value) {
            addCriterion("VALUE7 <>", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7GreaterThan(String value) {
            addCriterion("VALUE7 >", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE7 >=", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7LessThan(String value) {
            addCriterion("VALUE7 <", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7LessThanOrEqualTo(String value) {
            addCriterion("VALUE7 <=", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7Like(String value) {
            addCriterion("VALUE7 like", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7NotLike(String value) {
            addCriterion("VALUE7 not like", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7In(List<String> values) {
            addCriterion("VALUE7 in", values, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7NotIn(List<String> values) {
            addCriterion("VALUE7 not in", values, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7Between(String value1, String value2) {
            addCriterion("VALUE7 between", value1, value2, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7NotBetween(String value1, String value2) {
            addCriterion("VALUE7 not between", value1, value2, "value7");
            return (Criteria) this;
        }

        public Criteria andValue8IsNull() {
            addCriterion("VALUE8 is null");
            return (Criteria) this;
        }

        public Criteria andValue8IsNotNull() {
            addCriterion("VALUE8 is not null");
            return (Criteria) this;
        }

        public Criteria andValue8EqualTo(String value) {
            addCriterion("VALUE8 =", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8NotEqualTo(String value) {
            addCriterion("VALUE8 <>", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8GreaterThan(String value) {
            addCriterion("VALUE8 >", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE8 >=", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8LessThan(String value) {
            addCriterion("VALUE8 <", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8LessThanOrEqualTo(String value) {
            addCriterion("VALUE8 <=", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8Like(String value) {
            addCriterion("VALUE8 like", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8NotLike(String value) {
            addCriterion("VALUE8 not like", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8In(List<String> values) {
            addCriterion("VALUE8 in", values, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8NotIn(List<String> values) {
            addCriterion("VALUE8 not in", values, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8Between(String value1, String value2) {
            addCriterion("VALUE8 between", value1, value2, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8NotBetween(String value1, String value2) {
            addCriterion("VALUE8 not between", value1, value2, "value8");
            return (Criteria) this;
        }

        public Criteria andValue9IsNull() {
            addCriterion("VALUE9 is null");
            return (Criteria) this;
        }

        public Criteria andValue9IsNotNull() {
            addCriterion("VALUE9 is not null");
            return (Criteria) this;
        }

        public Criteria andValue9EqualTo(String value) {
            addCriterion("VALUE9 =", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9NotEqualTo(String value) {
            addCriterion("VALUE9 <>", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9GreaterThan(String value) {
            addCriterion("VALUE9 >", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9GreaterThanOrEqualTo(String value) {
            addCriterion("VALUE9 >=", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9LessThan(String value) {
            addCriterion("VALUE9 <", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9LessThanOrEqualTo(String value) {
            addCriterion("VALUE9 <=", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9Like(String value) {
            addCriterion("VALUE9 like", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9NotLike(String value) {
            addCriterion("VALUE9 not like", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9In(List<String> values) {
            addCriterion("VALUE9 in", values, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9NotIn(List<String> values) {
            addCriterion("VALUE9 not in", values, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9Between(String value1, String value2) {
            addCriterion("VALUE9 between", value1, value2, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9NotBetween(String value1, String value2) {
            addCriterion("VALUE9 not between", value1, value2, "value9");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VARIABLE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VARIABLE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}